### ISSUE TITLE
Library calculating incorrect CRC32?

### ISSUE THREAD

**Issue by sruthivarghese15** [griffo-io/Crc32#1]
I think there is some problem in calculating the crc. It's givivng different values from the online calculators.

I checked taking crc of a sing byte 0x03 and using the polynomial `0x04C11DB7u` and seed `0xffffffffu`. The expected output is `0x4B0BBE37`, but I'm getting` 4186413953` which is` 0xF9879B81`.

This is my code:
```
protected uint calculateCRC(byte[] array)
        {
            uint crc = Crc32Algorithm.Compute(0x04C11DB7u, 0xffffffffu, array);
            return crc;
        }
```
I'm using 

> .Net core 2.1

**Comment by dariogriffo** [comment]
Hi there, and sorry for the late response.
This repository is no longer maintained, please refer to another like Crc32.NET
Thanks

**Comment by sruthivarghese15** [comment]
Hi, but in that case I won't be able to give custom polynomial right?
